# .gitpod.yml
image:
  file: Dockerfile

tasks:
  - name: Setup and Start Services
    init: |
      echo "Setting up the development environment..."
      docker-compose build
    command: |
      echo "Starting all services..."
      docker-compose up

ports:
  - port: 3000
    onOpen: open-preview
    description: Next.js Frontend
  - port: 8000
    onOpen: open-browser
    description: FastAPI Backend
  - port: 5555
    onOpen: ignore
    description: Celery Flower
  - port: 5432
    onOpen: ignore
    description: PostgreSQL
  - port: 6379
    onOpen: ignore
    description: Redis

vscode:
  extensions:
    - ms-python.python
    - bradlc.vscode-tailwindcss
    - esbenp.prettier-vscode
